### ISSUE TITLE
Get rid of scrollbar

### ISSUE THREAD

**Issue by BenjaminHorn** [pzuraq/liquid-tether#25]
Great addon, I really like it. Although on the demo page in the flyout example  http://pzuraq.github.io/liquid-tether/#/examples?a=liquid-wormhole I found the appearing/disappearing scrollbar a little bit disturbing. Is it possible to get rid of it?

I have a routed modal which moves from down to up. During the animation scrollbar appears for a fraction of sec, then hides again, what shakes the whole screen.

**Comment by knownasilya** [comment]
Since this addon doesn't provide styles, it's up to the consumer to make those changes. You can do this simply with an `overflow: hidden;` on the `body`.

**Comment by BenjaminHorn** [comment]
taking a closer look at the code, target receive liquid-tether-target class

```CSS
body.liquid-tether-enabled {
  overflow: hidden;
}
```

**Comment by knownasilya** [comment]
Even better!

**Comment by knownasilya** [comment]
Seems like you'd want to use `overflow-x` if your app scrolls vertically.
