### ISSUE TITLE
Modal from modal

### ISSUE THREAD

**Issue by BenjaminHorn** [pzuraq/liquid-tether#29]
Is it possible to open a routed modal from a routed modal?
now:
**blog/post** shows post in a modal -> 
**blog/post/new** blog/post's modal animates out, blog/post/new animates in

Is there a way to open blog/post/new modal on top of blog/post modal?

**Comment by pzuraq** [comment]
In order to be able to animate between modals, each liquid-target can only display one item at a time. If you want to nest modals you should change the `to` property of the inner modal to a different target. It will automatically be given a higher z-index due to being added later.

**Comment by pzuraq** [comment]
@BenjaminHorn Do you still need help with this issue? If not I'm going to close

**Comment by BenjaminHorn** [comment]
@pzuraq TBH I did not the chance to try it out, and now I have to work on something else. I close it for now, and if I gonna have problem with it, I will report back to you.
