### ISSUE TITLE
Not working on 2.0.2 / 2.x versions

### ISSUE THREAD

**Issue by talhaobject90** [pzuraq/liquid-tether#32]
I wonder liquid-tether not working on ember 2.x versions. The installation and code in the template not raising any errors , but the modal is not showing up any more. Is it needed to copy the css files manually to make it work? . Another ember addon 'ember-modal-dialog' have to do like this to work..

**Comment by pzuraq** [comment]
You should not have to copy css files, it should automatically compile the css into your main css. You can confirm by looking for the `.liquid-tether` class in the output css that is built.

I've gotten reports about liquid-tether not working on 2.0, but I have not been able to reproduce. Can you give me more specific steps to reproduce this bug?

**Comment by pzuraq** [comment]
@talhaobject90 Any updates on this? I consider this a high priority issue, especially since you are not the first to report problems, but I still have not been able to reproduce.

**Comment by talhaobject90** [comment]
@pzuraq  , Sorry i was away from this for a couple of day... That's why lost tracking....  


```
package.json
{
  "name": "signlab-ember",
  "version": "0.0.0",
  "description": "Small description for signlab-ember goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "active-model-adapter": "2.0.3",
    "broccoli-asset-rev": "^2.2.0",
    "ember-cli": "1.13.12",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-bootstrap-datepicker": "0.5.5",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.1.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-notifications": "2.1.4",
    "ember-cli-qunit": "^1.0.4",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "2.0.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-select-2": "1.3.0",
    "ember-select-guru": "1.1.2",
    "liquid-fire": "0.21.3",
    "liquid-tether": "0.1.9"
  }
}
```



```
bower.json
{
  "name": "signlab-ember",
  "dependencies": {
    "ember": "2.0.2",
    "ember-cli-shims": "0.0.6",
    "ember-cli-test-loader": "0.2.1",
    "ember-data": "2.0.0",
    "ember-load-initializers": "0.1.7",
    "ember-qunit": "0.4.16",
    "ember-qunit-notifications": "0.1.0",
    "ember-resolver": "~0.1.20",
    "jquery": "^1.11.3",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.20.0",
    "bootstrap": "~3.3.5",
    "select2": "3.5.2",
    "bootstrap-datepicker": "~1.5.0"
  },
  "resolutions": {
    "ember": "2.0.2"
  }
}
```

```
app/templates/agents/new.hbs

{{agent-form type='ind' agent=model on-create=(action "createAgent")}}
{{outlet}}


<button {{action 'toggleHello'}} id="hello-world" class="btn btn-primary btn-embossed">
  Hello, World!
</button>

{{#if showHello}}
  {{#liquid-tether
    to="hello-world"
    target="#hello-world"
    attachment="middle left"
    target-attachment="middle right"
  }}
    <div id="hello-world-popover" class="popover right">
      <div class="arrow"></div>
      <div class="popover-title">
        Hello!
      </div>
    </div>
  {{/liquid-tether}}
{{/if}}
```

```
app/controllers/agents/new.js
import Ember from 'ember';

export default Ember.Controller.extend({


  actions: {

    createAgent: function(params) {


      var controller = this;
      var agent = this.store.createRecord('agent', {
        name: params.name,
        contactname: params.contactname,
        contactno: params.contactno,
        othcontactno: params.othcontactno,
        othrefdetails: params.othrefdetails,
        project_id: 1,
        // FIXME: fix project_id relationship ; 500 error comming in rails after save
      });
      agent.save().then(function(){


        controller.transitionToRoute('agents.agent' , agent);
      });
    },
    toggleHello() {
     this.toggleProperty('showHello');
   }
  }
});

```

```
app/transition.js


import { target } from 'liquid-tether';

export default function() {
  this.transition(
    this.hasClass('customer-info'),
    //this.toValue(true),
    this.use('toRight')

  );

  this.transition(
    this.fromRoute('projects.home'),
    this.toRoute('customers.new'),
    this.use('toRight'),
    this.reverse('toLeft')
  );


  this.transition(
  target('hello-world'),
  this.use('tether', ['to-up', {
    duration: 250,
    easing: 'easeInOutQuint'
  }])
);

this.transition(
  target('hello-world'),
  this.use('tether', ['to-up', {
    duration: 1500,
    easing: 'easeInOutQuint'
  }])
);
}
```

I tried all examples in the demo site http://pzuraq.github.io/liquid-tether/#/examples?a=hello-world 
But none is working.. 

You could checkout the complete app code here https://github.com/x303/signlab-ember

Thanks

**Comment by pzuraq** [comment]
Thanks for the response! So to be clear, the demo site is not working for you either?

Can you tell me which browser you are using and which operating system?

I'll probably get to this over the weekend, will update you as soon as I can!

**Comment by talhaobject90** [comment]
@pzuraq , Yes the demo site is not working for me at all.. 

I am using chrome Version 47.0.2526.80 (64-bit) / Ubuntu 14.04 LTS. 

Thanks... I love this addon, I will love you see it alive on my site....

**Comment by pzuraq** [comment]
That's very interesting. Are you running it locally and it's not working? Or are you running it at pzuraq.github.io/liquid-tether? I'm on OSX currently but been meaning to get Ubuntu going again, will install it and take a look this weekend :+1:

**Comment by talhaobject90** [comment]
All my attempt on local machine failed, I didn't tried it online yet. I am doing all the examples at pzuraq.github.io/liquid-tether . I don't think, it's bcoz of the OS, have you tried with my package.json /bower.json configuration? (I am trying it with ember 2.0.2 and ember data 2.0)..

I suggest to try one more time before switching to ubuntu. Why to bear that pain changing OS? 

Good Luck!!

**Comment by pzuraq** [comment]
I have run the demo site with Ember 2.0.2 on my local, using ember-try. I'm using Chrome Canary and Chrome 47.0.2526.106 (64-bit) and everything is working as expected. I've been meaning to install a flavor of Linux anyways, so this is kind of an excuse :wink: 

I'll let you know if I am able to reproduce with linux. Hopefully we'll get this resolved quickly.

**Comment by pzuraq** [comment]
@talhaobject90 Just giving a quick update, was very busy over the holidays but I'm back now and will be working on this over the next couple days. I'll ping you if I'm still unable to reproduce.

**Comment by talhaobject90** [comment]
@pzuraq  , Okay Friend , take your own time, i just skipped using this plugin in my current project. Any way i may need it on my next one. Could you give me the way you implemented on the demo app ? (that you told it's working with ember 2.0.2 version , I believe it's not the problem of the Operating system.). Please send me the code you made it worked in ember 2.0.2 version.

Thanks.

**Comment by pzuraq** [comment]
@talhaobject90 No problem. The demo app's code is located in `/tests/dummy/app`. If you clone the liquid-tether repo, you should be able to launch it by going into the addon's folder and doing `ember s`.

```
$ git clone https://github.com/pzuraq/liquid-tether.git
$ cd liquid-tether
$ ember s
```

And then just visit `localhost:4200` like any other ember app.

**Comment by talhaobject90** [comment]
@pzuraq , 

I tried cloning the app to my local machine. 

Even with ember 1.13 version and 2.2.0 version i am getting this error
```
Uncaught Error: Assertion Failed: Ember Views require jQuery between 1.7 and 2.1assert @ ember.debug.js:5921assert @ ember.debug.js:15630(anonymous function) @ ember.debug.js:43129internalRequire @ ember.debug.js:78internalRequire @ ember.debug.js:74internalRequire @ ember.debug.js:74requireModule @ ember.debug.js:44(anonymous function) @ ember.debug.js:54800(anonymous function) @ ember.debug.js:54802
loader.js:110 Uncaught Error: Could not find module `ember` imported from `dummy/app`
```

But as you could see ,  my bower includes jquery     "jquery": "^1.11.3", . 

What could be wrong here?

**Comment by pzuraq** [comment]
That's a bug that was just introduced into Ember-CLI. Jquery 1.12 was released and that broke everything. Change the dependency in the app's bower.json to be jquery 1.11.

Best,

- Chris G.

**Comment by benbabics** [comment]
Bump. @pzuraq have you been able to reproduce this, or has there been a fix? I am using for the first time on a 2.3.0 project, and when I use the liquid-wormhole, it isn't including any CSS. I am using `ember-cli-sass`, so not sure if I need to import anything? Any help is much appreciated.

**Comment by pzuraq** [comment]
@benbabics still have not beenableto reproduce, I am currently using liquid tether in Ember 2.2+ projects without issue.

I'm curious about the CSS you've mentioned, liquid tether is just an animation layer. The only styles that are included set things like positioning to get the animations working correctly. Are those styles not being included? Or do you mean the styles of the modals/flyouts themselves in the demo application?

**Comment by benbabics** [comment]
Ok so there is styling for `.liquid-target` and `.liquid-child`, but there isn't any styling for `.flyout-liquid-target`, `.flyout` and `.modal-backdrop`. Should I style that myself, or is there base styling provided for that? I wasn't sure what to expect, so maybe it's not so much a bug :)

**Comment by pzuraq** [comment]
Ah, yeah there is no base styling for any of those classes. Liquid tetheris style agnostic, you provide your own styles. That way it doesn't push you into a corner with how to structure your styling :smile: 

I will make a note to add that to the documentation. For now you can copy the styles from the dummy app if you'd like to use them as a base to build on. I can also look into adding an option to build the addon with the styles, so that you could get them OOTB.

**Comment by benbabics** [comment]
Oh ok... no worries... I can do that myself. I wasn't clear on if there were base styles for this or not. Thx for the clarification.

**Comment by pzuraq** [comment]
I looked into this again and am still unable to reproduce the issue. Using the code @talhaobject90 posted above in a fresh app made with `ember new`, everything seems to work. If someone can post a failing example app I'm happy to take a look, but for now I'm cloning this issue.

**Comment by talhaobject90** [comment]
@pzuraq , Thanks friend, i know you did the best , No problem, we could look into it later, I will try some thing with another os/combination. Let's close this for now.
