### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getState' of undefined

### ISSUE THREAD

**Issue by admarrs** [pzuraq/liquid-tether#40]
Trying a simple fullscreen-modal example, all seems to work but on insert and removal I get the follwoing error:
```
Uncaught TypeError: Cannot read property 'getState' of undefined
```
It seems to be due to contextClass being undefined in the liquid-target service:
```
target = {
          name: targetName,
          items: Ember.A(),
          class: `${targetName}-liquid-target`,
          contextClass: item.get('targetClass'),
          firstTime: true
        };
```
Where is the targetClass set?

**Comment by pzuraq** [comment]
`targetClass` is set directly on the `liquid-tether` like so

```
{{#liquid-tether targetClass="..."}}
```

Strange that it's causing this error, it should be nullable and is null by default. I will look into this asap.

**Comment by pzuraq** [comment]
@admarrs it looks like this might be an error caused by the Ember Inspector: https://github.com/emberjs/ember.js/issues/12885

Can you confirm?

**Comment by admarrs** [comment]
For me it turned out to be an issue with my css styling. I was using flexbox for the main body and reverting back to non-flexbox stying got rid of the error.

I can't now re-produce it so am closing the issue.
