### ISSUE TITLE
Overflow hidden

### ISSUE THREAD

**Issue by epyx25** [pzuraq/liquid-tether#47]
I use liquid tether often in my projects. Thanks for this great addon!
Today I faced  the following problem. I try to use https://github.com/btecu/ember-cli-bootstrap-datetimepicker in a template but the bootstrap dropdown-menu gets cropped, because `.liquid-container ` has` overflow: hidden`.
![image](https://cloud.githubusercontent.com/assets/17404207/14043922/2bcb36e6-f28a-11e5-8a00-6e40fb23a551.png)

Is there a workaround for this? How should dropdowns handled?

**Comment by pzuraq** [comment]
Ah yeah, this will be a problem. There are two possible solutions:

1. Use `liquid-tether` for the internal dropdown as well. `liquid-tether`s actually stack in different frames and are managed using the `liquid-target-service` and `liquid-target-container` under the hood, so if you place a `liquid-tether` inside of another `liquid-tether`, it'll appear on a new layer on top of the old one. However, that would mean rewriting the datetime picker addon which you probably don't want to do.

2. Try to remove the `overflow: hidden` constraint on `.liquid-container`s _inside_ `liquid-target-container`. It's been a while but if I remember correctly, the `overflow: hidden` style is added by liquid-fire for things like `liquid-if`s and such where you're animating on the same page. With `liquid-tether`, the animation container is essentially the entire page, so you may be able to remove that style and have things still work depending on your animations.

Option 2 is hackier, but it may work. I'm not entirely sure though, the overflow settings are tricky to work with as is. If I get some time today I'll see if I can reproduce your example and figure out a way to do it.

**Comment by epyx25** [comment]
Thanks for taking the time to investigate it. For now I force the calendar's orientation to bottom, and I set a minimum height for the `liquid-child`. Not an optimal solution, but it works.

**Comment by pzuraq** [comment]
@epyx25 Going to close this issue for now, let me know if it's still a problem for you.
