### ISSUE TITLE
breaks ember fastboot

### ISSUE THREAD

**Issue by maerten** [pzuraq/liquid-tether#49]
This plugin seems to be incompatible with ember fastboot. (Using ember-cli 2.4.3)

    $ ember fastboot --serve-assets
    Installing FastBoot npm dependencies
    document is not defined
    ReferenceError: document is not defined
    fastboot-dist/fastboot/vendor/tether/tether.js:408:1
    fastboot-dist/fastboot/vendor/tether/tether.js:417:1
    fastboot-dist/fastboot/vendor/tether/tether.js:9:1
    fastboot-dist/fastboot/vendor/tether/tether.js:11:1

**Comment by pzuraq** [comment]
I'm not sure there's an easy way around this. Tether.js is a hard dependency of liquid-tether, and it does a lot of positioning using the document unfortunately.

Reading through the code, this shouldn't be a problem if you aren't using Liquid Tether for the route you are rendering, references to `document` only start when the functions are actually called. If they still are occurring (i.e. just including Liquid Tether without even using it causes the problem) we can probably do a better job of wrapping Tether in a module.

If you are looking to get a similar animation style and also want to render the page using fastboot, I would recommend using the underlying library [Liquid Wormhole](https://github.com/pzuraq/liquid-wormhole). We could also build an alternative, fastboot-compliant positioning engine and use it with Liquid Wormhole, sounds like something that might be pretty necessary.

**Comment by maerten** [comment]
It seems that ember fastboot (jshint?) is doing some checking for any undefined globals. This same issue came up with another plugn (ember-bootstrap) referencing a global 'jQuery' object.

A fix or alternative to tether.js would be great, this library seems to be most developed popup/overlay library available on emberaddons.com, and would benefit greatly from being fastboot compatible. I'd be happy to help out with testing.

**Comment by pzuraq** [comment]
Hmmm, if that's the case there's probably a way we can A. Turn off tethering features if we're rendering with fastboot and B. Tell fastboot it's ok, those hooks won't be being used.

There is another set of problems though as liquid tether uses the didInsertElement hook which is also not supported. I'll have to think about a way to degrade gracefully in Fastboot mode, it's definitely a priority for this project.

**Comment by ynnoj** [comment]
This is [fixed](https://github.com/HubSpot/tether/blob/v1.2.0/src/js/tether.js#L24-L37) in `tether.js` 1.2.0. 

I have a working, tested fork of the add-on (https://github.com/ynnoj/liquid-tether/commit/1a03ae17e1f2fb079bdaa4bcd741d2bf42482954).

@pzuraq The projects current dependency is your fork of `tether.js` that is quite far behind master. Not sure how you want to proceed.

**Comment by pzuraq** [comment]
Will update my Tether.js fork today! Thanks for bringing this up!

**Comment by pzuraq** [comment]
Updated Tether.js and merged the latest. Let me know if this solves the fastboot problem, would love for it to be that easy!

**Comment by ynnoj** [comment]
Maybe not :(

**Comment by pzuraq** [comment]
I figured it might not 😕 

The core problem is that `liquid-wormhole` itself performs a lot of DOM manipulation, and that simply isn't available in fastboot. I'd like to solve this issue, but I'm not quite sure how to do it yet.

In an ideal world, I think we would render the page without doing anything at all essentially, and then once the page is loaded `liquid-tether` would kick in begin doing its DOM manipulation thing. That means no modals showing in previews and such unfortunately, but I'm not sure there's another way around the issue.

**Comment by davidpett** [comment]
@pzuraq I just submitted https://github.com/pzuraq/liquid-wormhole/pull/4 that fixes liquid-wormhole for fastboot compliancy

**Comment by pzuraq** [comment]
Merged @davidpett's PR, he's reporting that liquid-tether works with fastboot now! I'll be trying it out soon, closing this issue for now.
