### ISSUE TITLE
It's not working in Safari

### ISSUE THREAD

**Issue by btecu** [pzuraq/liquid-tether#5]
The animations and arrows (css) seems to have some issues with Safari 8.

**Comment by pzuraq** [comment]
Thanks for pointing this out! I've been testing in Safari 9 on the El Capitan beta, Safari handles fixed element rendering a bit differently than the other major browsers. I'll take a look asap.

**Comment by pzuraq** [comment]
@btecu I haven't been able to find any issues with the animations in Safari 8 on my VM. The CSS for the arrows is definitely off, but that's not a liquid-tether issue. Can you describe the issues you're encountering with more detail?

**Comment by btecu** [comment]
Here's the arrow issue:
<img width="246" alt="arrow" src="https://cloud.githubusercontent.com/assets/7517745/10417664/dd1d4bc4-7011-11e5-9725-22fb43225d2a.png">

The animation seems to work better now although it looks like it has 5 fps - while on Chrome is smooth:
![anim](https://cloud.githubusercontent.com/assets/7517745/10417666/fe4c9ec6-7011-11e5-86c5-4ed0a6286cd4.gif)
