### ISSUE TITLE
Applying the same animation to multiple targets with dynamic to property

### ISSUE THREAD

**Issue by steffenbrem** [pzuraq/liquid-tether#50]
How can you use `liquid-tether` to bind to target elements inside an each loop and animate them all in the same way? I don't see a way how this can currently be achieved.

```hbs
{{#each posts as |post|}}
<li>
    <span id="post-{{post.id}}">{{post.title}}</span>
    {{#liquid-tether to="?" target=(concat "#post-" post.id)}}
        <div class="my-tooltip">{{post.titleInfo}}</div>
    {{/liquid-tether}}
</li>
{{/each}}
```

```js
// transitions.js
import { target } from 'liquid-tether';

this.transition(
    target('How do we handle dynamic stuff here?')
);
```

Simply using `{{liquid-tether to="something"}}` will not work as it will override the outlet and only render the last one.

**Comment by pzuraq** [comment]
I don't see why not. `liquid-tether` manages a series of layers on a top layer of the DOM, and each tether gets it's own layer. By default the layers shouldn't interact, and there isn't a background element unless you add it via styles (there is one, but it's styles make it effectively invisible).

It seems like you want a tooltip though, can I ask how you want to show these tooltips? Will they all be visible at all times? If you want to, say, show them on hover, I would recommend something more like this:

```handlebars
{{#each posts as |post|}}
<li>
    {{#post-list-item as |postTitleIsHovered|}}
        <span id="post-{{post.id}}>{{post.title}}</span>
        {{#if postTitleIsHovered}}
            {{#liquid-tether to="post-list-item" target=(concat "#post-" post.id)}}
                <div class="my-tooltip">{{post.titleInfo}}</div>
            {{/liquid-tether}}
        {{/if}}
    {{/post-list-item}}
</li>
{{/each}}
```

Where the `post-list-item` component is responsible for checking and updating if the `span` is hovered. This logic can be made more general, or more specific, depending on your use case.

The power of `ember-tether` and `liquid-tether` is that they allow you to use the standard handlebars conditional logic to control the display of your tethered items. Be it a modal, a popover, or a tooltip, all you have to do is put it inside of an `if` statement 😄 

If you do want to show all of the tooltips at once though and it's not working let me know, I can try to reproduce the issue and find out what's wrong.

**Comment by steffenbrem** [comment]
Thanks for taking time to look into this :smiley:. Just as in your example, my first try was to use the same `to` parameter for every `liquid-tether` component. But it will only render the last one. If I make the `to` parameter unique for every `liquid-tether` component, they will all show correctly. But since the target is used for the animation selector it is not a good solution to make every to unique IMO.

**Comment by steffenbrem** [comment]
In the image below you can see the result when use the following template (excluded noise to make it more clear):

```hbs
{{! some html stuff... }}
{{#liquid-tether to="post-list-item" target="#post-1" attachment='top right' targetAttachment='bottom right'}}
    <div style="background: red">
        This is tethered!
        <button type="button" {{action "save"}}>Save</button>
    </div>
{{/liquid-tether}}
{{! some html stuff... }}

{{! some html stuff... }}
{{#liquid-tether to="post-list-item" target="#post-2" attachment='top right' targetAttachment='bottom right'}}
    <div style="background: red">
        This is tethered!
        <button type="button" {{action "save"}}>Save</button>
    </div>
{{/liquid-tether}}
{{! some html stuff... }}
```

![Screen](http://puu.sh/oaYFu/e640f3ebb1.png)

**Comment by pzuraq** [comment]
Ah yeah, I see what you're getting at. If you are trying to show multiple items at once you will need to have a unique `to` parameter for each `liquid-tether`, and this may be a performance concern.

It still seems like you only want to show one item at a time though, right? Will the user always see that menu, or will they only see it when they hover on the gear?

**Comment by steffenbrem** [comment]
Well a tooltip was maybe a bad example indeed. In my real application its more a dropdown and multiple dropdowns could be open at the same time (maybe that is my design flaw, idk). It would be cool if you could use the same animation for multiple outlets.

**Comment by pzuraq** [comment]
Ah, so the root problem is applying the same animation to multiple targets which potentially have a dynamic `to` property, meaning we can't easily match the animation

Ok, that definitely seems like an issue. I'll get to work on a PR to add some sort of matching functionality so you can match on a pattern instead of just on the individual selector.

**Comment by steffenbrem** [comment]
That would be a very nice feature, I am sure! Thanks for your help. :heart:
