### ISSUE TITLE
CSS transform makes modal look blurry in Chrome

### ISSUE THREAD

**Issue by lolmaus** [pzuraq/liquid-tether#54]
Here's how my modal looks:

![image](https://cloud.githubusercontent.com/assets/200884/14799113/a3e1a238-0b43-11e6-92ab-66b762dcc028.png)

Here's how it looks after disabling the inline style applied to the `.liquid-tether-element`:

![image](https://cloud.githubusercontent.com/assets/200884/14799141/b977cc62-0b43-11e6-99c6-c76377914572.png)

I've tried a couple of fixes from StackOverflow but they didn't work. 

The `transform` style looks like this: `translateX(234px) translateY(80px) translateZ(0px)`.

I've discovered that the amount of blur depends on viewport width. When I gradually resize the window, the modal goes from blurred to not blurred then to blurred again in a cycle.

**Comment by pzuraq** [comment]
Unfortunately the inline styles that are applied here are applied by Tether.js and this project does not have any influence over how they do their positioning. I'd suggest opening an issue on the Tether project, or rolling your own positioning logic and using [liquid-wormhole](https://github.com/pzuraq/liquid-wormhole), which provides the animation without rhe positioning.

**Comment by pzuraq** [comment]
Just curious, what platform is this occuring on? I haven't noticed any blurring issues but I'm on Mac, this might also be considered a Chrome bug.
