### ISSUE TITLE
Option to place wormhole into another location

### ISSUE THREAD

**Issue by knownasilya** [pzuraq/liquid-tether#61]
Basically trying to have the modals show up in the acceptance tests, by having them appear inside the testing container element instead of the body.

**Comment by pzuraq** [comment]
The modal container should be placed relative to the application root, not the body necessarily. It should be in the testing container. Is that not occuring in your tests?

**Comment by pzuraq** [comment]
Because of the fixed styles applied to the modal container, it may appear that they are being positioned relative to the body and not the test container. Not sure if that's what you're seeing.

**Comment by knownasilya** [comment]
Will check again (more closely :)) and get back to you.

**Comment by pzuraq** [comment]
Any word on this? Triaging issues today, let me know if this is still a problem and if so I'll look into it!

**Comment by knownasilya** [comment]
Not an issue I think.
