### ISSUE TITLE
Access to old docs

### ISSUE THREAD

**Issue by bryanhickerson** [pzuraq/liquid-tether#65]
I'm not ready to migrate to v2, and I still need access to the v1 documentation. Is there some way to access it?

**Comment by pzuraq** [comment]
The docs on in the dummy app, for now you can clone the repo, checkout the support branch, and run the dummy app to see them locally:

```
git clone https://github.com/pzuraq/liquid-tether.git
cd liquid-tether
git checkout support/1.x
ember s
```

I'll see if I can figure out a way to get them hosted again somewhere as well.

**Comment by bryanhickerson** [comment]
Upgraded to v2, no longer need access to old docs.
