### ISSUE TITLE
Documentation is woefully inaccurate

### ISSUE THREAD

**Issue by egee-irl** [pzuraq/liquid-tether#66]
The documentation for this plugin is grossly sparse and misleading at worst. There are references to adding liquid-tether to both templates _and_ components in different sections of the interactive documentation. The parameters section claims there are only two required parameters but another section claims there are three.

The documentation also assumes the user has prior experience with _both_ Liquid Fire and Ember Tether. The examples referring to transition map make no effort to explain what the map is or where the code belongs.

I suggest either updating the documentation or point users at the documentation for the prerequisite libraries.

**Comment by pzuraq** [comment]
Are you using the beta for v2? Not sure where you read that three parameters are required. If you are using v1, three were required back then, but now all you need are `target` and `attachment` to actually use a tether.

If you want to add animations, you do have to use Liquid Fire. I do link to it on the first page, and I don't believe it's Liquid Tether's responsibility to explain how Liquid Fire works as it is pretty much the standard Ember animation library. It does make sense to provide a more clear link to that documentation though. There are links to the Tether.js docs on the [parameters page](http://pzuraq.github.io/liquid-tether/#/docs/parameters), I think they have all you need to know about Tether.

Sorry you had trouble reading through the docs, I work on Liquid Tether in my spare time so sometimes they aren't as polished as I'd like. Specific suggestions would definitely help (where should I add links, what concepts other libraries should be explained) and pull requests are always welcome.
