### ISSUE TITLE
Maybe should check target to ensure it exists before tethering

### ISSUE THREAD

**Issue by jfarlow** [pzuraq/liquid-tether#69]
(I've fixed my own code to avoid the situation, but this might be a useful check to consider.)

In addTether(bodyElement) function, the target is checked to ensure it is not null, but does not seem to check whether the target is actually in the DOM.

In this way, when there are dynamic tethers/targets between various pages, it is possible for a page to request a target that is no longer on the DOM.  This false target ID is passed to a new tether in the addTether() function, and crashes tether.js when it tries to adjust the (non-existent) target element's class.

It might cost some cycles, but maybe useful to put a check for the existence of a target in the DOM prior to actually creating a new tether in addTether().

**Comment by pzuraq** [comment]
I do think this should throw an error, if the DOM selector isn't there then there should be a clear reason for the failure. If I remember correctly though this isn't so clear in Tether itself. We can add an assert that throws an error with a clear message about the selector not existing.
